---
- hosts: all
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Create file
      file:
        path: /home/ansible/condition.txt
        state: touch
