   - name: Start HTTPD
     ansible.builtin.service:
       name: "{{ src }}"
       state: started
       enabled: yes

   - name: Allow on FW
     ansible.posix.firewalld:
       service: http
       permanent: true
       state: enabled
       immediate: true
